name: Build

on:
  pull_request:
    branches: [ "develop" ]
  push:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      build_version: 1.0.${{github.run_number}}
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7
          fetch-depth: 0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build StegoProject.sln  /p:Version=${{env.build_version}} --no-restore
        
      - name: Test with the dotnet CLI
        run: dotnet test